name: tf-stream
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - tensorflow==2.6.2
  - osmnx==0.15.1
  - streamlit==1.3.1
  - streamlit-folium
  - holoviews
  - hvplot
  - altair
